# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Polyphonie de la psychiatrie
subtitle: Des histoires pour une histoire

description: >
  Psyphonie est un support audiovisuel composé de témoignages d’une trentaine d’«acteurs» et «actrices» du champ psychiatrique. Ils et elles sont infirmiers, psychologues, musicothérapeutes, psychiatres, maîtres socio-professionnels, aides-soignantes, personnes ayant vécu une hospitalisation en psychiatrie, architectes, éducateurs, proches de patients, philosophes, neuroscientifiques, pharmacologues, historiens, guides de musée.
  Chaque personne a été interviewée selon le même canevas sur un fond unique, et nous avons obtenu ainsi environ septante heures de témoignage.
  Par ces différentes mises en récit, nous voulons souligner le fait que tous les savoirs sur la psychiatrie font sens.
  Les récits filmés visent à amener un degré de conscience historique, clinique, critique, et à sensibiliser les professionnels de la santé et le grand public aux enjeux de l’histoire, mais aussi à la multitude d’expériences vécues qui ont marqué et marquent encore la psychiatrie.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://psyphonie.ch" # the base hostname & protocol for your site

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - npm-shrinkwrap.json
  - node_modules
  - README.md
  - "*.sh"

keep_files:
  - api
